### ISSUE TITLE
Problem installing Windows/Python 3.13

### ISSUE THREAD

**Issue by highfestiva** [aresch/pyenet#35]
It works fine to install under Python 3.11, however in Python 3.13 I'm getting:

```
enet.c(807): fatal error C1083: Cannot open include file: 'enet/types.h': No such file or directory
```

when trying to `pip install -U pyenet`. I can neither find the types.h file — nor the enet directory — on disk when attempting `pip install -v --no-clean pyenet`. These are the files present:

```
./.eggs
./.eggs/Cython-0.29.37-py3.13.egg/...
./.eggs/README.txt
./build
./build/temp.win-amd64-cpython-313
./build/temp.win-amd64-cpython-313/Release
./ChangeLog
./dist
./dist/pyenet-1.3.17.tar.gz
./enet.c
./enet.pyx
./LICENSE
./MANIFEST.in
./PKG-INFO
./pyenet.egg-info
./pyenet.egg-info/dependency_links.txt
./pyenet.egg-info/PKG-INFO
./pyenet.egg-info/requires.txt
./pyenet.egg-info/SOURCES.txt
./pyenet.egg-info/top_level.txt
./README.rst
./setup.cfg
./setup.py
./test_client.py
./test_enet.py
./test_server.py
```

I don't know how it's supposed to fetch the source files, or if they are supposed to be part of the package? Thanks for any help!

**Comment by qaxl** [comment]
skill issue

**Comment by biggus-developerus** [comment]
You're meant to fetch the enet source files yourself (https://github.com/aresch/pyenet/blob/master/setup.py#L12)

**Comment by biggus-developerus** [comment]
The [PyPi version of pyenet](https://github.com/piqueserver/pyenet/) seems to be broken. Try building this one from source, and if you run into issues, you can use my [fork](https://github.com/biggus-developerus/pyenet/), which works fine with Python 3.13 (Tested it just now).
